/* =====================================================================
   TransformerProcure Intelligence — dashboard controller
   ===================================================================== */
const App = (() => {
  const state = {
    page: 'dashboard',
    masters: null, live: null, config: null,
    filters: { commodity: 'CU', provider: '', product: '', period: '365D' },
    bomJob: '', sensCommodity: 'CU', fcCommodity: 'CU',
    cache: {},
  };

  /* ------------------------------------------------------------ chrome */
  function setBanner(live) {
    const host = U.el('bannerHost');
    if (!host) return;
    const parts = [];
    if (live?.demo_data) {
      parts.push(`<div class="banner warn">
        <span class="pill demo"><span class="dot"></span>Demo data</span>
        <span><b>Simulated price history.</b> These figures are generated by a seeded
        model, not sourced from any market. Connect a licensed feed or import official
        producer circulars before using them commercially.</span>
        <span class="spacer"></span>
        <span class="faint mono">history to ${U.esc(live.latest_price_date || '—')}</span>
      </div>`);
    }
    // Name the commodities that are actually stale or simulated. A single
    // producer circular landing does not make copper current, and a global
    // "all clear" would overstate the data on the rest of the screen.
    if (live && live.banner) {
      const per = (live.commodities || []).filter(c => c.status !== 'CURRENT');
      parts.push(`<div class="banner err">
        <span class="pill stale"><span class="dot"></span>Not current</span>
        <span>${U.esc(live.banner)}.
        ${per.map(c => `<b>${U.esc(c.commodity)}</b> ${U.esc(c.status.toLowerCase())}`).join(' · ')}
        — see <a href="#" onclick="App.go('settings');return false">Settings</a> to connect a source.</span>
      </div>`);
    }
    host.innerHTML = parts.join('');
  }

  function setStatus(txt, kind) {
    const n = U.el('statusPill');
    if (!n) return;
    n.className = 'pill ' + (kind || '');
    n.innerHTML = `<span class="dot"></span>${U.esc(txt)}`;
  }

  /* --------------------------------------------------------- navigation */
  function go(page) {
    state.page = page;
    document.querySelectorAll('.nav button').forEach(b =>
      b.classList.toggle('active', b.dataset.page === page));
    document.querySelectorAll('.page').forEach(p =>
      p.classList.toggle('active', p.id === 'page-' + page));
    window.scrollTo({ top: 0, behavior: 'instant' });
    const fn = renderers[page];
    if (fn) fn();
    setTimeout(Charts.resizeAll, 60);
  }

  /* ============================ 1. DASHBOARD ========================== */
  function renderDashboard() {
    const d = {};
    API.progressive({
      kpis: API.kpis(), exec: API.executive(), summary: API.summary(),
      alerts: API.alerts(), impact: API.impact(), coverage: API.coverage(),
      monthly: API.monthly(), recos: API.recommendations(),
    }, {
      kpis: v => { d.kpis = v; paintKpis(d); },
      exec: v => { d.exec = v; paintExec(d); },
      recos: v => { d.recos = v; paintSignals(d); },
      summary: v => { d.summary = v; paintSummary(d); },
      impact: v => { d.impact = v; paintImpact(d); },
      coverage: v => { d.coverage = v; paintCoverage(d); },
      alerts: v => { d.alerts = v; renderAlertList('dashAlerts', v.alerts.slice(0, 6)); },
      monthly: v => { d.monthly = v; paintMonthly(v, 'chartMonthly'); },
      __error: (k, e) => console.warn('[dashboard]', k, e.message),
    }, () => setStatus('Updated ' + new Date().toLocaleTimeString('en-IN'), 'live'));
  }

  function paintKpis(d) {
    /* KPI strip */
    if (d.kpis) {
      const cards = d.kpis.cards.filter(c => c.available);
      U.html('kpiStrip', cards.map(c => {
        const dir = U.dirClass(c.change_pct);
        const fc = c.forecast_30d_pct != null
          ? `<span class="tag ${c.forecast_30d_pct > 0 ? 'bad' : 'good'}">30d fc ${U.pct(c.forecast_30d_pct, 1)}</span>` : '';
        return `<div class="kpi ${dir}">
          <div class="k-label" title="${U.esc(c.label)}">${U.esc(c.label)}</div>
          <div class="k-value">${U.rs(c.current)} <span class="k-unit">/MT</span></div>
          <div class="k-row">
            ${U.chg(c.change_pct)}
            <span class="faint mono">30d ${U.pct(c.d30, 1)}</span>
            <span class="faint mono">1y ${U.pct(c.d365, 1)}</span>
          </div>
          <div class="k-row">${fc}${U.dataClassTag(c.data_class)}</div>
          <div class="k-foot" title="${U.esc(c.source || '')}">
            ${c.source_currency ? `${c.source_currency} ${U.num(c.source_price, 0)}/${c.source_unit} · ` : ''}${U.esc(c.as_of || '')}
          </div>
        </div>`;
      }).join(''));
    }
  }

  function paintExec(d) {
    /* executive block */
    if (d.exec) {
      const e = d.exec;
      U.html('execBlock', `
        <div class="grid g4">
          <div class="card">
            <div class="card-head"><h3>Total commodity exposure</h3></div>
            <div class="k-value mono" style="font-size:24px">${U.inr(e.total_exposure)}</div>
            <div class="card-note">Current market value of all commodity content across
              ${Object.keys(e.exposure).length} materials in the live order book.</div>
          </div>
          <div class="card">
            <div class="card-head"><h3>30-day forecast exposure</h3></div>
            <div class="k-value mono" style="font-size:24px">${U.inr(e.forecast_exposure['30d'])}</div>
            <div class="k-row">${U.chg(e.total_exposure ? e.potential_exposure_30d / e.total_exposure * 100 : 0)}
              <span class="faint">${U.inr(e.potential_exposure_30d)} potential</span></div>
          </div>
          <div class="card">
            <div class="card-head"><h3>Overall commodity risk</h3></div>
            <div><span class="signal ${e.overall_risk === 'HIGH' ? 'nolock' : e.overall_risk === 'MEDIUM' ? 'partial' : 'buy'}">${U.esc(e.overall_risk)}</span></div>
            <div class="k-row" style="margin-top:8px">
              ${Object.entries(e.risk).map(([c, r]) =>
                `<span class="tag ${r.risk_band === 'HIGH' ? 'bad' : r.risk_band === 'MEDIUM' ? 'warn' : 'good'}">${c} ${r.risk_band}</span>`).join('')}
            </div>
          </div>
          <div class="card">
            <div class="card-head"><h3>Top project at risk</h3></div>
            ${e.top_project_at_risk ? `
              <div class="k-value mono" style="font-size:17px">${U.esc(e.top_project_at_risk.job_no)}</div>
              <div class="faint">${U.esc(e.top_project_at_risk.customer || '')} · ${e.top_project_at_risk.rating_mva} MVA × ${e.top_project_at_risk.quantity}</div>
              <div class="k-row"><span class="tag bad">${U.esc(e.top_project_at_risk.commodity)} ${U.inr(e.top_project_at_risk.exposure)}</span></div>
              <div class="card-note">${U.esc(e.top_project_at_risk.quadrant)}</div>` : '<div class="faint">No projects loaded</div>'}
          </div>
        </div>`);
    }
  }

  function paintSignals(d) {
    /* procurement signals */
    if (d.recos) {
      U.html('signalBlock', d.recos.rows.filter(r => ['CU', 'AL'].includes(r.commodity)).map(r => `
        <div class="card">
          <div class="card-head">
            <h3>${r.commodity === 'CU' ? 'Copper' : 'Aluminium'} — procurement signal</h3>
            <span class="spacer"></span>
            <span class="tag ${r.confidence === 'HIGH' ? 'good' : r.confidence === 'LOW' ? 'warn' : 'info'}">${r.confidence} confidence</span>
          </div>
          <div style="display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin-bottom:10px">
            <span class="signal ${U.signalClass(r.signal)}">${U.esc(r.signal)}</span>
            <div class="kv" style="flex:1;min-width:180px">
              <dt>Score</dt><dd>${U.num(r.score, 1)}</dd>
              <dt>Suggested cover</dt><dd>${U.num(r.suggested_cover_pct, 0)}%</dd>
              <dt>Suggested lot</dt><dd>${U.num(r.suggested_lot_mt, 2)} MT</dd>
            </div>
          </div>
          <ul class="reason-list">${r.reasons.slice(0, 4).map(x => `<li>${U.esc(x)}</li>`).join('')}</ul>
          <div class="card-note">Factor scores —
            ${Object.entries(r.factors).map(([k, v]) =>
              `${k} <b class="mono">${v > 0 ? '+' : ''}${U.num(v, 0)}</b>`).join(' · ')}
          </div>
        </div>`).join(''));
    }
  }

  function paintSummary(d) {
    /* management summary */
    if (d.summary) {
      U.html('summaryBlock', `
        <ul class="reason-list" style="font-size:12.5px;line-height:1.75">
          ${d.summary.sentences.map(s => `<li>${U.esc(s)}</li>`).join('')}
        </ul>
        <div class="card-note">Generated ${U.ago(d.summary.generated_at)} from live figures —
          no sentence in this summary is hard-coded.</div>`);
    }
  }

  function paintImpact(d) {
    /* material impact table */
    if (d.impact) {
      const rows = d.impact.rows;
      U.html('impactTable', U.table([
        { label: 'Commodity', key: 'commodity', cls: 'mono' },
        { label: 'BOM MT/trf', num: true, render: r => U.num(r.bom_mt_per_transformer, 3) },
        { label: 'Total req MT', num: true, render: r => U.num(r.total_requirement_mt, 2) },
        { label: 'Current price', num: true, render: r => U.rs(r.current_price) },
        { label: 'Expected change', num: true, render: r =>
            `<span class="chg ${U.dirClass(r.price_change)}">${r.price_change >= 0 ? '+' : ''}${U.rs(r.price_change)}</span>` },
        { label: 'Impact/transformer', num: true, render: r => U.inr(r.impact_per_transformer) },
        { label: 'Total exposure', num: true, render: r => U.inr(r.total_exposure) },
        { label: 'Basis', render: r => `<span class="faint">${U.esc(r.basis)}</span>` },
      ], rows) + `<div class="card-note">
        Total impact per transformer <b class="mono">${U.inr(d.impact.total_impact_per_transformer)}</b>
        · total project exposure <b class="mono">${U.inr(d.impact.total_project_exposure)}</b>
        across ${d.impact.units} transformers.
        Impact = expected price change × BOM consumption × quantity.</div>`);
    }
  }

  function paintCoverage(d) {
    /* coverage */
    if (d.coverage) {
      U.html('coverageTable', U.table([
        { label: 'Commodity', key: 'commodity', cls: 'mono' },
        { label: 'Requirement MT', num: true, render: r => U.num(r.requirement_mt, 2) },
        { label: 'Stock', num: true, render: r => U.num(r.stock_mt, 2) },
        { label: 'Open PO', num: true, render: r => U.num(r.open_po_mt, 2) },
        { label: 'Confirmed', num: true, render: r => U.num(r.confirmed_mt, 2) },
        { label: 'Uncovered MT', num: true, render: r => `<b>${U.num(r.uncovered_mt, 2)}</b>` },
        { label: 'Coverage', num: true, render: r => {
            // A commodity with no coverage record is "not tracked", which is a
            // different claim from "0% covered" — never render it as exposure.
            if (!r.tracked || r.coverage_pct == null)
              return '<span class="tag flat">not tracked</span>';
            const p = r.coverage_pct;
            const cls = p >= 70 ? 'good' : p >= 40 ? 'warn' : 'bad';
            return `<div style="display:flex;align-items:center;gap:6px;justify-content:flex-end">
              <div class="bar-track" style="width:56px"><div class="bar-fill ${cls}" style="width:${Math.min(p, 100)}%"></div></div>
              <span>${U.num(p, 0)}%</span></div>`; } },
        { label: 'Uncovered exposure', num: true, render: r =>
            r.uncovered_exposure == null ? '<span class="faint">—</span>' : U.inr(r.uncovered_exposure) },
      ], d.coverage.rows));
    }
  }

  function paintMonthly(m, target) {
    if (m && m.months.length) {
      Charts.bars(target, m.months,
        m.series.filter(s => s.values.some(v => v > 0))
          .map(s => ({ name: s.commodity, data: s.values })),
        { stack: true, unit: 'INR exposure' });
    } else Charts.empty(target, 'No delivery-dated projects');
  }

  /* ====================== 2 & 3. COPPER / ALUMINIUM =================== */
  async function renderCopper() {
    const d = await API.all({
      series: API.series({ commodity: 'CU', provider: 'BME', product: 'CU_CATHODE', period: '3Y' }),
      parity: API.parity(), fc: API.forecast('CU'), reco: API.recommendation('CU'),
      lme: API.series({ commodity: 'CU', provider: 'LME', product: 'CU_CATHODE', period: '3Y' }),
    });

    if (d.series?.available) {
      Charts.priceLine('chartCuPrice', d.series.points,
        { name: 'Copper cathode (India)', mas: ['ma30', 'ma90', 'ma200'] });
      U.html('cuStats', statBlock(d.series, d.fc));
    }
    if (d.parity?.available) {
      const p = d.parity;
      const s = p.series;
      Charts.multiLine('chartCuParity', s.map(x => x.date), [
        { name: 'LME equivalent (INR)', data: s.map(x => x.lme_inr), color: Charts.C.blue },
        { name: 'India reference', data: s.map(x => x.india), color: Charts.C.amber },
      ], { zoom: true });
      Charts.multiLine('chartCuPremium', s.map(x => x.date),
        [{ name: 'Premium over LME', data: s.map(x => x.premium), color: Charts.C.teal }]);
      U.html('cuParity', `
        <dl class="kv">
          <dt>LME cash</dt><dd>USD ${U.num(p.lme_usd, 2)} /MT</dd>
          <dt>USD/INR</dt><dd>${U.num(p.usdinr, 4)}</dd>
          <dt>LME equivalent</dt><dd>${U.rs(p.lme_inr_equivalent)}</dd>
          <dt>India reference</dt><dd>${U.rs(p.india_price)}</dd>
          <dt>Premium over LME</dt><dd>${U.rs(p.premium)} (${U.num(p.premium_pct, 2)}%)</dd>
          <dt>90-day avg premium</dt><dd>${U.rs(p.premium_avg_90)}</dd>
          <dt>1-year premium range</dt><dd>${U.rs(p.premium_min_1y)} – ${U.rs(p.premium_max_1y)}</dd>
          <dt>Basis</dt><dd><span class="tag ${p.basis_status === 'WIDE' ? 'bad' : p.basis_status === 'NARROW' ? 'good' : 'flat'}">${p.basis_status}</span></dd>
        </dl>
        <div class="card-note">Indian equivalent = LME USD/MT × USD/INR.
          Premium = India reference − LME equivalent.
          FX source: ${U.esc(p.usdinr_source)}.</div>`);
    }
    if (d.reco?.available) U.html('cuReco', recoCard(d.reco));
    if (d.fc?.available) renderForecastInto('chartCuForecast', 'cuForecastTable', d.fc);
  }

  async function renderAluminium() {
    const d = await API.all({
      compare: API.compare('AL'), stats: API.alStats(),
      series: API.series({ commodity: 'AL', provider: 'NALCO', product: 'AL_INGOT', period: '3Y' }),
      reco: API.recommendation('AL'), fc: API.forecast('AL'),
    });

    if (d.compare) {
      U.html('alCompare', d.compare.table.map(t => `
        <div class="card">
          <div class="card-head"><h3>${U.esc(t.product.replace('AL_', 'Aluminium ').replace('WIREROD', 'Wire Rod'))}</h3>
            <span class="spacer"></span>
            <span class="tag ${t.spread_pct > 2 ? 'warn' : 'flat'}">spread ${U.num(t.spread_pct, 2)}%</span></div>
          ${U.table([
            { label: 'Provider', key: 'provider', cls: 'mono' },
            { label: 'Price INR/MT', num: true, render: r => U.rs(r.price) },
            { label: 'vs average', num: true, render: r =>
                `<span class="chg ${U.dirClass(r.vs_avg_pct)}">${U.pct(r.vs_avg_pct)}</span>` },
            { label: '30d', num: true, render: r => U.pct(r.d30, 1) },
            { label: '', render: r => r.is_lowest ? '<span class="tag good">Lowest</span>' : '' },
          ], t.entries, { rowClass: r => r.is_lowest ? 'best' : '' })}
          <div class="card-note">Lowest ${U.esc(t.lowest_provider)} ${U.rs(t.lowest)} ·
            highest ${U.esc(t.highest_provider)} ${U.rs(t.highest)} ·
            average ${U.rs(t.average)} · spread ${U.rs(t.spread)}/MT</div>
        </div>`).join(''));

      const hist = d.compare.spread_history?.AL_INGOT;
      if (hist?.length) {
        Charts.multiLine('chartAlSpread', hist.map(x => x.date),
          [{ name: 'Producer spread (ingot)', data: hist.map(x => x.spread), color: Charts.C.violet }],
          { unit: 'INR / MT' });
      }
      // provider price comparison chart
      const prods = d.compare.table;
      if (prods.length) {
        Charts.bars('chartAlProviders', prods.map(t => t.product.replace('AL_', '')),
          ['NALCO', 'BALCO', 'HINDALCO'].map(pv => ({
            name: pv, data: prods.map(t => (t.entries.find(e => e.provider === pv) || {}).price ?? 0),
          })), { unit: 'INR / MT' });
      }
    }
    if (d.stats) {
      U.html('alStatsTable', U.table([
        { label: 'Provider', key: 'provider', cls: 'mono' },
        { label: 'Product', render: r => r.product.replace('AL_', '') },
        { label: 'Current', num: true, render: r => U.rs(r.current) },
        { label: '30d avg', num: true, render: r => U.rs(r.avg_30) },
        { label: '3m avg', num: true, render: r => U.rs(r.avg_90) },
        { label: '12m avg', num: true, render: r => U.rs(r.avg_365) },
        { label: 'Low', num: true, render: r => U.rs(r.min_all) },
        { label: 'High', num: true, render: r => U.rs(r.max_all) },
        { label: 'Percentile', num: true, render: r =>
            `<span class="tag ${r.percentile > 70 ? 'bad' : r.percentile < 30 ? 'good' : 'flat'}">${U.num(r.percentile, 0)}% ${U.esc(r.zone)}</span>` },
        { label: '30d', num: true, render: r => U.pct(r.d30, 1) },
      ], d.stats.rows));
    }
    if (d.series?.available) {
      Charts.priceLine('chartAlPrice', d.series.points, { name: 'NALCO ingot', mas: ['ma30', 'ma90'] });
      U.html('alStats', statBlock(d.series, d.fc));
    }
    if (d.reco?.available) U.html('alReco', recoCard(d.reco));
  }

  /* ======================== 4. HISTORICAL ============================ */
  async function renderHistorical() {
    const f = state.filters;
    const q = { commodity: f.commodity, period: f.period };
    if (f.provider) q.provider = f.provider;
    if (f.product) q.product = f.product;
    let s;
    try { s = await API.series(q); }
    catch (e) { Charts.empty('chartHistory', 'No data for this selection'); U.html('histStats', ''); return; }
    if (!s.available) return;

    Charts.priceLine('chartHistory', s.points, { mas: ['ma7', 'ma30', 'ma90', 'ma200'] });
    Charts.multiLine('chartWeekly', s.monthly.map(m => m.date), [
      { name: 'Monthly average', data: s.monthly.map(m => m.avg), color: Charts.C.amber },
      { name: 'Monthly high', data: s.monthly.map(m => m.high), color: Charts.C.bad },
      { name: 'Monthly low', data: s.monthly.map(m => m.low), color: Charts.C.good },
    ]);
    U.html('histStats', statBlock(s, null));
    U.html('histTable', U.table([
      { label: 'Month', key: 'date' },
      { label: 'Open', num: true, render: r => U.rs(r.open) },
      { label: 'High', num: true, render: r => U.rs(r.high) },
      { label: 'Low', num: true, render: r => U.rs(r.low) },
      { label: 'Close', num: true, render: r => U.rs(r.close) },
      { label: 'Average', num: true, render: r => U.rs(r.avg) },
      { label: 'Range', num: true, render: r => U.rs(r.high - r.low) },
    ], [...s.monthly].reverse().slice(0, 24)));
    U.html('histMeta', `<div class="card-note">
      ${s.points.length} observations · sources: ${s.sources.map(U.esc).join(', ')} ·
      classes: ${s.data_classes.map(U.dataClassTag).join(' ')}</div>`);
  }

  /* ========================= 5. FORECAST ============================= */
  async function renderForecast() {
    const c = state.fcCommodity;
    const d = await API.all({ fc: API.forecast(c), lb: API.leaderboard(c), vol: API.volatility() });
    if (d.fc?.available) {
      renderForecastInto('chartForecast', 'forecastTable', d.fc);
      const t = d.fc.trend, v = d.fc.volatility, b = d.fc.band;
      U.html('fcContext', `
        <div class="grid g3">
          <div class="card"><div class="card-head"><h3>Trend classification</h3></div>
            <div><span class="signal ${t.score > 15 ? 'nolock' : t.score < -15 ? 'buy' : 'monitor'}">${U.esc(t.trend)}</span></div>
            <dl class="kv" style="margin-top:9px">
              ${Object.entries(t.components || {}).map(([k, val]) =>
                `<dt>${U.esc(k.replace('_', ' '))} (${Math.round((t.weights[k] || 0) * 100)}%)</dt><dd>${val > 0 ? '+' : ''}${U.num(val, 0)}</dd>`).join('')}
              <dt><b>Composite</b></dt><dd><b>${U.num(t.score, 1)}</b></dd>
            </dl>
            <div class="card-note">Weighted blend of moving-average structure, momentum,
              forecast direction, historical percentile and 30-day slope.</div></div>
          <div class="card"><div class="card-head"><h3>Volatility</h3></div>
            <div id="gaugeVol" class="chart sm" style="height:150px"></div>
            <dl class="kv">
              <dt>7-day</dt><dd>${U.num(v.v7, 1)}%</dd>
              <dt>30-day</dt><dd>${U.num(v.v30, 1)}%</dd>
              <dt>90-day</dt><dd>${U.num(v.v90, 1)}%</dd>
              <dt>Annualised</dt><dd>${U.num(v.annualised, 1)}%</dd>
              <dt>Band</dt><dd><span class="tag ${v.band === 'EXTREME' || v.band === 'HIGH' ? 'bad' : v.band === 'MEDIUM' ? 'warn' : 'good'}">${U.esc(v.band)}</span></dd>
            </dl></div>
          <div class="card"><div class="card-head"><h3>Procurement price band</h3></div>
            <div class="k-value mono" style="font-size:19px">${U.esc(b.zone)}</div>
            <div class="faint" style="margin-bottom:8px">${U.num(b.percentile, 0)}th percentile of ${b.observations} observations</div>
            <div class="bar-track" style="height:8px"><div class="bar-fill ${b.percentile > 70 ? 'bad' : b.percentile < 30 ? 'good' : 'warn'}" style="width:${b.percentile}%"></div></div>
            <dl class="kv" style="margin-top:9px">
              <dt>Historical low</dt><dd>${U.rs(b.low)}</dd>
              <dt>Average</dt><dd>${U.rs(b.average)}</dd>
              <dt>Current</dt><dd><b>${U.rs(b.current)}</b></dd>
              <dt>Historical high</dt><dd>${U.rs(b.high)}</dd>
            </dl>
            <div class="card-note">0–10% very low · 10–30% low · 30–70% normal ·
              70–90% high · 90–100% very high</div></div>
        </div>`);
      Charts.gauge('gaugeVol', v.index, v.band);
    } else {
      Charts.empty('chartForecast', d.fc?.message || 'No forecast stored — run a refresh');
    }

    if (d.lb?.leaderboard) {
      const horizons = Object.keys(d.lb.leaderboard).sort((a, b) => +a - +b);
      U.html('leaderboard', horizons.map(h => {
        const rows = d.lb.leaderboard[h].filter(r => r.mape != null).slice(0, 8);
        return `<div class="card">
          <div class="card-head"><h3>${h}-day horizon back-test</h3></div>
          ${U.table([
            { label: 'Model', key: 'model', cls: 'mono' },
            { label: 'MAPE %', num: true, render: r => U.num(r.mape, 3) },
            { label: 'MAE', num: true, render: r => U.num(r.mae, 0) },
            { label: 'RMSE', num: true, render: r => U.num(r.rmse, 0) },
            { label: 'Folds', num: true, key: 'folds' },
            { label: '', render: r => r.selected ? '<span class="tag good">Selected</span>' : '' },
          ], rows, { rowClass: r => r.selected ? 'best' : '' })}</div>`;
      }).join('') + `<div class="card-note">${U.esc(d.lb.method || '')}</div>`);
    } else {
      U.html('leaderboard', '<div class="chart-empty">Back-test detail is generated on the next forecast run.</div>');
    }

    if (d.vol) {
      U.html('volTable', U.table([
        { label: 'Commodity', key: 'commodity', cls: 'mono' },
        { label: 'Daily %', num: true, render: r => U.num(r.daily, 2) },
        { label: '7d ann.', num: true, render: r => U.num(r.v7, 1) },
        { label: '30d ann.', num: true, render: r => U.num(r.v30, 1) },
        { label: '90d ann.', num: true, render: r => U.num(r.v90, 1) },
        { label: 'Annualised', num: true, render: r => `<b>${U.num(r.annualised, 1)}%</b>` },
        { label: 'Index', num: true, render: r => U.num(r.index, 0) },
        { label: 'Band', render: r =>
            `<span class="tag ${r.band === 'EXTREME' || r.band === 'HIGH' ? 'bad' : r.band === 'MEDIUM' ? 'warn' : 'good'}">${U.esc(r.band)}</span>` },
      ], d.vol.rows));
    }
  }

  function renderForecastInto(chartId, tableId, fc) {
    const paths = fc.paths || {};
    const key = Object.keys(paths).find(k => String(k) === '30') || Object.keys(paths)[0];
    Charts.forecastChart(chartId, fc.history || [], paths[key] || []);
    U.html(tableId, U.table([
      { label: 'Horizon', render: r => `${r.horizon_days} days` },
      { label: 'Target date', render: r => U.date(r.target_date) },
      { label: 'Forecast', num: true, render: r => `<b>${U.rs(r.forecast_price)}</b>` },
      { label: 'vs today', num: true, render: r => {
          const p = fc.last_price ? (r.forecast_price - fc.last_price) / fc.last_price * 100 : null;
          return U.chg(p, 2); } },
      { label: 'Lower 95%', num: true, render: r => U.rs(r.lower_ci) },
      { label: 'Upper 95%', num: true, render: r => U.rs(r.upper_ci) },
      { label: 'Direction', render: r =>
          `<span class="tag ${r.direction === 'UP' ? 'bad' : r.direction === 'DOWN' ? 'good' : 'flat'}">${U.esc(r.direction)}</span>` },
      { label: 'Model', key: 'model_used', cls: 'mono' },
      { label: 'MAPE %', num: true, render: r => U.num(r.mape, 2) },
      { label: 'Confidence', render: r =>
          `<span class="tag ${r.confidence === 'HIGH' ? 'good' : r.confidence === 'LOW' ? 'bad' : 'warn'}">${U.esc(r.confidence)}</span>` },
    ], fc.results) + `<div class="card-note">${U.esc(fc.disclaimer || '')}</div>`);
  }

  /* ======================= 6. BOM & EXPOSURE ========================= */
  function renderBom() {
    API.progressive({
      roll: API.rollup(), waterfall: API.waterfall(state.bomJob || null),
      sens: API.sensitivity(state.sensCommodity), matrix: API.matrix(),
      monthly: API.monthly(), flow: API.flow(state.sensCommodity, state.bomJob || null),
    }, {
      roll: v => paintBomRoll({ roll: v }),
      waterfall: v => paintWaterfall({ waterfall: v }),
      sens: v => paintSensitivity({ sens: v }),
      matrix: v => paintMatrix({ matrix: v }),
      flow: v => paintFlow({ flow: v }),
      monthly: v => paintMonthly(v, 'chartBomMonthly'),
      __error: (k, e) => console.warn('[bom]', k, e.message),
    });
  }

  function paintBomRoll(d) {
    if (d.roll) {
      const t = d.roll.transformers;
      U.html('bomJobSelect', `<option value="">All projects (portfolio)</option>` +
        t.map(x => `<option value="${U.esc(x.job_no)}" ${state.bomJob === x.job_no ? 'selected' : ''}>
          ${U.esc(x.job_no)} — ${x.rating_mva} MVA × ${x.quantity}</option>`).join(''));

      U.html('bomTransformers', U.table([
        { label: 'Job', key: 'job_no', cls: 'mono' },
        { label: 'Customer', render: r => U.esc(r.customer || '—') },
        { label: 'MVA', num: true, render: r => U.num(r.rating_mva, 1) },
        { label: 'Ratio', render: r => U.esc(r.voltage_ratio || '') },
        { label: 'Qty', num: true, key: 'quantity' },
        { label: 'Cu MT', num: true, render: r => U.num(r.copper_mt_project, 3) },
        { label: 'Al MT', num: true, render: r => U.num(r.aluminium_mt_project, 3) },
        { label: 'Material/unit', num: true, render: r => U.inr(r.material_cost_per_unit) },
        { label: 'vs BOM rate', num: true, render: r => U.chg(r.material_variance_pct) },
        { label: 'Project cost', num: true, render: r => U.inr(r.project_total_cost) },
        { label: 'Delivery', render: r => U.date(r.delivery_date) },
        { label: 'Status', render: r => `<span class="tag flat">${U.esc(r.status || '')}</span>` },
      ], d.roll.transformers));

      const byC = d.roll.by_commodity;
      U.html('bomByCommodity', U.table([
        { label: 'Commodity', key: 'commodity', cls: 'mono' },
        { label: 'Requirement MT', num: true, render: r => U.num(r.requirement_mt, 3) },
        { label: 'Current value', num: true, render: r => U.inr(r.current_value) },
        { label: 'Value at BOM rate', num: true, render: r => U.inr(r.bom_value) },
        { label: 'Variance', num: true, render: r => U.inr(r.variance) },
        { label: 'Variance %', num: true, render: r => U.chg(r.variance_pct) },
      ], Object.entries(byC).map(([k, v]) => ({ commodity: k, ...v }))));

      Charts.bars('chartExposureMix',
        Object.keys(byC), [{ name: 'Current value', data: Object.values(byC).map(v => v.current_value) }],
        { unit: 'INR' });
    }
  }

  function paintWaterfall(d) {
    if (d.waterfall?.available) {
      const w = d.waterfall;
      Charts.waterfall('chartWaterfall', w.steps, w.original_cost_per_transformer);
      U.html('waterfallMeta', `<dl class="kv">
        <dt>Scope</dt><dd>${U.esc(w.label)}</dd>
        <dt>Base cost / transformer</dt><dd>${U.inr(w.base_cost)}</dd>
        <dt>Material cost / transformer</dt><dd>${U.inr(w.material_cost)}</dd>
        <dt>Original cost / transformer</dt><dd>${U.inr(w.original_cost_per_transformer)}</dd>
        <dt>Commodity impact</dt><dd>${U.inr(w.total_impact_per_transformer)}</dd>
        <dt>Revised cost / transformer</dt><dd><b>${U.inr(w.revised_cost_per_transformer)}</b></dd>
        <dt>Cost increase</dt><dd>${U.pct(w.increase_pct)}</dd>
        <dt>Project impact</dt><dd>${U.inr(w.project_impact)}</dd>
      </dl><div class="card-note">Impacts use the 30-day forecast per commodity unless
        you override them in the what-if simulator.</div>`);
    }
  }

  function paintSensitivity(d) {
    if (d.sens?.available) {
      const s = d.sens;
      Charts.multiLine('chartSensitivity', s.rows.map(r => `${r.scenario_pct > 0 ? '+' : ''}${r.scenario_pct}%`), [
        { name: 'Transformer cost', data: s.rows.map(r => r.transformer_cost), color: Charts.C.amber },
      ], { unit: 'INR / transformer' });
      U.html('sensTable', U.table([
        { label: 'Scenario', render: r => `${r.scenario_pct > 0 ? '+' : ''}${r.scenario_pct}%` },
        { label: `${s.commodity} price`, num: true, render: r => U.rs(r.price) },
        { label: 'Material cost', num: true, render: r => U.inr(r.material_cost_this_commodity) },
        { label: 'Transformer cost', num: true, render: r => U.inr(r.transformer_cost) },
        { label: 'Δ / transformer', num: true, render: r =>
            `<span class="chg ${U.dirClass(r.transformer_delta)}">${U.inr(r.transformer_delta)}</span>` },
        { label: 'Project cost', num: true, render: r => U.inr(r.project_cost) },
        { label: 'Project exposure', num: true, render: r => U.inr(r.project_exposure) },
      ], s.rows, { rowClass: r => r.is_current ? 'best' : '' }) +
        `<div class="card-note">${s.commodity} consumption
          ${U.num(s.consumption_mt_per_transformer, 3)} MT per transformer ×
          ${s.units} transformers = ${U.num(s.total_requirement_mt, 2)} MT total requirement.</div>`);
    }
  }

  function paintMatrix(d) {
    if (d.matrix) {
      Charts.scatter('chartMatrix', d.matrix.items);
      const quads = { 'HIGH RISK / HIGH EXPOSURE': [], 'HIGH RISK / LOW EXPOSURE': [],
                      'LOW RISK / HIGH EXPOSURE': [], 'LOW RISK / LOW EXPOSURE': [] };
      d.matrix.items.forEach(i => { (quads[i.quadrant] ||= []).push(i); });
      U.html('matrixQuads', Object.entries(quads).map(([q, items]) => `
        <div class="quad ${q === 'HIGH RISK / HIGH EXPOSURE' ? 'critical' : ''}">
          <h4>${U.esc(q)}${q === 'HIGH RISK / HIGH EXPOSURE' ? ' — critical priority' : ''}</h4>
          ${items.length ? items.slice(0, 6).map(i =>
            `<div class="quad-item"><span>${U.esc(i.job_no)} · ${U.esc(i.commodity)}</span>
             <span>${U.inr(i.exposure)}</span></div>`).join('')
            : '<div class="faint" style="font-size:11px">None</div>'}
        </div>`).join(''));
    }
  }

  function paintFlow(d) {
    if (d.flow) {
      const f = d.flow;
      const step = (label, value) =>
        `<div class="flow-step"><span class="f-label">${label}</span><span class="f-value">${value}</span></div>`;
      const arrow = '<div class="flow-arrow"></div>';
      U.html('flowChain', [
        step(`${f.commodity} price (${U.esc(f.provider)} ${U.esc(f.product)})`, U.rs(f.price) + ' /MT'),
        step('BOM consumption per transformer', U.num(f.consumption_mt_per_transformer, 4) + ' MT'),
        step('Material cost per transformer', U.inr(f.material_cost_per_transformer)),
        step('Transformer quantity', f.quantity + ' nos'),
        step('Total commodity exposure', U.inr(f.total_exposure)),
        step(`Forecast price (${f.forecast_horizon_days}d)`, U.rs(f.forecast_price) + ' /MT'),
        step('Forecast exposure', U.inr(f.forecast_exposure)),
        step('Potential exposure', U.inr(f.potential_exposure)),
        step('Procurement recommendation',
          `<span class="signal ${U.signalClass(f.recommendation)}">${U.esc(f.recommendation)}</span>`),
      ].join(arrow));
    }
  }

  /* ========================== 7. QUOTES ============================= */
  async function renderQuotes() {
    let d;
    try { d = await API.quotes(); } catch (e) { return; }
    U.html('quotesTable', U.table([
      { label: 'Supplier', render: r => U.esc(r.supplier) },
      { label: 'Commodity', render: r => `${U.esc(r.commodity)} / ${U.esc(r.product || '—')}` },
      { label: 'Quote date', render: r => U.date(r.quote_date) },
      { label: 'Valid until', render: r => r.valid_until
          ? `${U.date(r.valid_until)} ${r.expired ? '<span class="tag bad">expired</span>'
            : r.days_to_expiry <= 7 ? `<span class="tag warn">${r.days_to_expiry}d</span>` : ''}` : '—' },
      { label: 'Quoted', num: true, render: r => `${U.num(r.price, 0)} ${U.esc(r.currency)}/${U.esc(r.unit)}` },
      { label: 'Basic INR/MT', num: true, render: r => U.rs(r.effective_price) },
      { label: 'Freight', num: true, render: r => U.rs(r.freight) },
      { label: 'Tax %', num: true, render: r => U.num(r.tax_pct, 0) },
      { label: 'Landed cost', num: true, render: r => `<b>${U.rs(r.landed_cost)}</b>` },
      { label: 'Benchmark', num: true, render: r => U.rs(r.benchmark) },
      { label: 'vs market', num: true, render: r => U.chg(r.variance_pct) },
      { label: 'vs prev quote', num: true, render: r => r.variance_vs_prev != null ? U.rs(r.variance_vs_prev) : '—' },
      { label: 'MOQ', num: true, render: r => r.moq_mt ? U.num(r.moq_mt, 1) + ' MT' : '—' },
      { label: 'Terms', render: r => U.esc(r.payment_terms || '—') },
      { label: 'Lead', num: true, render: r => r.delivery_days ? r.delivery_days + ' d' : '—' },
      { label: 'Status', render: r => {
          const m = { 'BEST PRICE': 'good', 'BELOW MARKET': 'good',
                      'ABOVE MARKET': 'bad', 'EXPIRED QUOTE': 'warn' };
          return r.status_flag ? `<span class="tag ${m[r.status_flag] || 'flat'}">${U.esc(r.status_flag)}</span>` : '—'; } },
      { label: '', render: r => `<button class="btn sm" onclick="App.deleteQuote(${r.id})">Delete</button>` },
    ], d.quotes, { rowClass: r => r.status_flag === 'BEST PRICE' ? 'best' : '' }));

    U.html('quotesNote', `<div class="card-note">
      <b>Basic INR/MT</b> is the supplier's ex-plant rate normalised to INR per tonne — this is
      what is benchmarked, because the published market reference is itself ex-plant.
      <b>Landed cost</b> adds premium and freight and grosses up by tax; it is what ranks
      suppliers. Each quote is compared against its own product, so a wire-rod quote is never
      scored against an ingot reference.</div>`);
  }

  async function submitQuote(ev) {
    ev.preventDefault();
    const f = new FormData(ev.target);
    const body = Object.fromEntries(f.entries());
    ['price', 'freight', 'premium', 'tax_pct', 'moq_mt'].forEach(k => {
      if (body[k] === '') delete body[k]; else if (body[k] != null) body[k] = parseFloat(body[k]);
    });
    if (body.delivery_days === '') delete body.delivery_days;
    else if (body.delivery_days) body.delivery_days = parseInt(body.delivery_days, 10);
    Object.keys(body).forEach(k => { if (body[k] === '') delete body[k]; });
    try {
      await API.createQuote(body);
      U.toast('Quotation saved and benchmarked', 'ok');
      ev.target.reset();
      renderQuotes();
    } catch (e) { U.toast('Could not save quote: ' + e.message, 'err'); }
  }
  async function deleteQuote(id) {
    try { await API.deleteQuote(id); U.toast('Quote deleted', 'ok'); renderQuotes(); }
    catch (e) { U.toast('Delete failed: ' + e.message, 'err'); }
  }

  /* ========================== 8. ALERTS ============================= */
  function renderAlertList(target, alerts) {
    if (!alerts?.length) {
      U.html(target, '<div class="chart-empty">No open alerts</div>');
      return;
    }
    U.html(target, alerts.map(a => `
      <div class="alert-row ${U.esc(a.severity)}">
        <div class="a-body">
          <div class="a-title">${U.esc(a.title)}
            <span class="tag ${a.severity === 'CRITICAL' ? 'bad' : a.severity === 'WARNING' ? 'warn' : 'info'}">${U.esc(a.severity)}</span>
            ${a.commodity ? `<span class="tag flat">${U.esc(a.commodity)}</span>` : ''}</div>
          <div class="a-msg">${U.esc(a.message)}</div>
        </div>
        <div style="display:flex;flex-direction:column;align-items:flex-end;gap:5px">
          <span class="a-time">${U.ago(a.triggered_at)}</span>
          <button class="btn sm" onclick="App.ackAlert(${a.id})">Ack</button>
        </div>
      </div>`).join(''));
  }
  async function renderAlerts() {
    try {
      const d = await API.alerts();
      renderAlertList('alertList', d.alerts);
      U.html('alertCount', d.alerts.length + ' open');
    } catch (e) {}
  }
  async function ackAlert(id) {
    try { await API.ackAlert(id); renderAlerts(); renderDashboardAlerts(); } catch (e) {}
  }
  async function renderDashboardAlerts() {
    try { const d = await API.alerts(); renderAlertList('dashAlerts', d.alerts.slice(0, 6)); }
    catch (e) {}
  }
  async function evaluateAlerts() {
    try {
      const r = await API.evaluateAlerts();
      U.toast(`Evaluated ${r.evaluated_rules} rules — ${r.count} new alert(s)`, 'ok');
      renderAlerts();
    } catch (e) { U.toast('Evaluation failed: ' + e.message, 'err'); }
  }

  /* ========================= 9. REPORTS ============================= */
  async function renderReports() {
    const d = await API.all({
      kpis: API.procKpis(), backtest: API.costBacktest(state.bomJob || null),
      quality: API.quality(), log: API.sourceLog(),
    });

    if (d.kpis) {
      U.html('procKpis', Object.values(d.kpis.kpis).map(k => `
        <div class="card">
          <div class="card-head"><h3>${k.commodity} — supply chain KPIs</h3></div>
          <dl class="kv">
            <dt>Market price</dt><dd>${U.rs(k.market_price)}</dd>
            <dt>Benchmark average</dt><dd>${U.rs(k.benchmark_avg_period)}</dd>
            <dt>Average buying price</dt><dd>${U.rs(k.average_buying_price)}</dd>
            <dt>Purchase timing gain / MT</dt><dd class="${k.purchase_timing_gain_per_mt > 0 ? '' : ''}">${U.rs(k.purchase_timing_gain_per_mt)}</dd>
            <dt>Price avoidance (total)</dt><dd>${U.inr(k.price_avoidance)}</dd>
            <dt>Quantity purchased</dt><dd>${U.num(k.quantity_purchased_mt, 2)} MT</dd>
            <dt>Total spend</dt><dd>${U.inr(k.total_spend)}</dd>
            <dt>BOM rate</dt><dd>${U.rs(k.bom_rate)}</dd>
            <dt>BOM vs market</dt><dd>${U.pct(k.bom_vs_market_pct)}</dd>
            <dt>Market vs PO rate</dt><dd>${U.pct(k.market_vs_po_pct)}</dd>
            <dt>Coverage</dt><dd>${U.num(k.coverage_pct, 1)}%</dd>
            <dt>Open PO coverage</dt><dd>${U.num(k.open_po_coverage_pct, 1)}%</dd>
            <dt>Uncovered exposure</dt><dd>${U.inr(k.uncovered_exposure)}</dd>
            <dt>Commodity cost exposure</dt><dd>${U.inr(k.commodity_cost_exposure)}</dd>
            <dt>Best supplier</dt><dd>${U.esc(k.best_supplier || '—')}</dd>
            <dt>Best landed</dt><dd>${U.rs(k.best_supplier_landed)}</dd>
            <dt>Worst supplier</dt><dd>${U.esc(k.worst_supplier || '—')}</dd>
            <dt>Supplier variance</dt><dd>${U.pct(k.supplier_price_variance_pct)}</dd>
            <dt>Forecast MAPE</dt><dd>${U.num(k.forecast_accuracy_mape, 2)}%</dd>
            <dt>Forecast model</dt><dd style="font-size:10px">${U.esc(k.forecast_model || '—')}</dd>
          </dl>
        </div>`).join(''));
    }

    if (d.backtest?.available) {
      const b = d.backtest;
      Charts.multiLine('chartCostBacktest', b.series.map(p => p.date), [
        { name: 'Total transformer cost', data: b.series.map(p => p.total_cost), color: Charts.C.amber },
        { name: 'Material cost only', data: b.series.map(p => p.material_cost), color: Charts.C.blue },
      ], { unit: 'INR / transformer', zoom: true });
      U.html('backtestMeta', `<dl class="kv">
        <dt>Scope</dt><dd>${U.esc(b.label)}</dd>
        <dt>Lowest historical cost</dt><dd>${U.inr(b.min_cost)}</dd>
        <dt>Highest historical cost</dt><dd>${U.inr(b.max_cost)}</dd>
        <dt>Current cost</dt><dd><b>${U.inr(b.current_cost)}</b></dd>
        <dt>Peak-to-trough swing</dt><dd>${U.num(b.swing_pct, 1)}%</dd>
      </dl><div class="card-note">${U.esc(b.note)}</div>`);
    }

    if (d.quality) {
      U.html('qualityTable', U.table([
        { label: 'Series', render: r => `${U.esc(r.commodity)} / ${U.esc(r.provider)} / ${U.esc(r.product)}` },
        { label: 'Observations', num: true, key: 'observations' },
        { label: 'From', render: r => U.date(r.first) },
        { label: 'To', render: r => U.date(r.last) },
        { label: 'Missing days', num: true, render: r =>
            `<span class="tag ${r.missing_business_days > 20 ? 'warn' : 'flat'}">${r.missing_business_days}</span>` },
        { label: 'Jumps', num: true, render: r =>
            `<span class="tag ${r.jumps ? 'warn' : 'flat'}">${r.jumps}</span>` },
        { label: 'Outliers', num: true, key: 'outliers' },
        { label: 'Negative', num: true, render: r =>
            `<span class="tag ${r.negative_prices ? 'bad' : 'good'}">${r.negative_prices}</span>` },
        { label: 'Classes', render: r => r.data_classes.map(U.dataClassTag).join(' ') },
      ], d.quality.series));
    }

    if (d.log) {
      U.html('sourceLog', U.table([
        { label: 'Source', render: r => U.esc(r.source) },
        { label: 'Adapter', render: r => `<span class="mono">${U.esc(r.adapter || '')}</span>` },
        { label: 'Status', render: r => `<span class="tag ${r.status === 'SUCCESS' ? 'good' : r.status === 'UNAVAILABLE' ? 'warn' : 'bad'}">${U.esc(r.status)}</span>` },
        { label: 'Started', render: r => U.ago(r.started) },
        { label: 'Fetched', num: true, key: 'fetched' },
        { label: 'Inserted', num: true, key: 'inserted' },
        { label: 'Rejected', num: true, key: 'rejected' },
        { label: 'Duplicates', num: true, key: 'duplicates' },
        { label: 'Error', render: r => `<span class="faint" style="white-space:normal">${U.esc((r.error || '').slice(0, 120))}</span>` },
      ], d.log.runs, { empty: 'No source runs recorded yet — press Refresh data.' }));
    }
  }

  /* ========================= 10. SETTINGS =========================== */
  async function renderSettings() {
    const d = await API.all({
      cfg: API.config(), settings: API.settings(), live: API.live(),
      sched: API.scheduler(), stats: API.stats(),
    });

    if (d.cfg) {
      const c = d.cfg;
      U.html('cfgBlock', `<dl class="kv">
        <dt>Application</dt><dd>${U.esc(c.app)} ${U.esc(c.version)}</dd>
        <dt>Data mode</dt><dd>${U.esc(c.data_mode)}</dd>
        <dt>Database</dt><dd>${U.esc(c.database)}</dd>
        <dt>Scheduler</dt><dd>${c.scheduler_enabled ? 'enabled' : 'disabled'}</dd>
        <dt>Daily fetch</dt><dd>${U.esc(c.schedules.daily)}</dd>
        <dt>Weekly retrain</dt><dd>${U.esc(c.schedules.weekly)}</dd>
        <dt>Monthly report</dt><dd>${U.esc(c.schedules.monthly)}</dd>
        <dt>Forecast horizons</dt><dd>${c.forecast_horizons.join(', ')} days</dd>
        <dt>Moving averages</dt><dd>${c.ma_windows.join(', ')} days</dd>
        <dt>Stale after</dt><dd>${c.stale_after_hours} h</dd>
      </dl>
      <div class="card-head" style="margin-top:12px"><h3>Forecast libraries</h3></div>
      <dl class="kv">${Object.entries(c.model_capabilities).filter(([k]) => k !== 'note')
        .map(([k, v]) => `<dt>${U.esc(k)}</dt><dd>${v ? '<span class="tag good">available</span>'
          : '<span class="tag flat">not installed</span>'}</dd>`).join('')}</dl>
      <div class="card-note">${U.esc(c.model_capabilities.note || '')}</div>`);

      U.html('sourceCfg', `<dl class="kv">
        ${Object.entries(c.sources_configured).map(([k, v]) =>
          `<dt>${U.esc(k.replace(/_/g, ' '))}</dt><dd>${v ? '<span class="tag good">configured</span>'
            : '<span class="tag warn">not configured</span>'}</dd>`).join('')}
      </dl><div class="card-note">${U.esc(c.note)}</div>`);
    }

    if (d.live) {
      U.html('sourceStatus', U.table([
        { label: 'Adapter', render: r => `<span class="mono">${U.esc(r.adapter)}</span>` },
        { label: 'Source', render: r => U.esc(r.source) },
        { label: 'Configured', render: r => r.configured ? '<span class="tag good">yes</span>'
            : `<span class="tag warn">missing ${U.esc((r.missing_config || []).join(', ') || 'setup')}</span>` },
        { label: 'Last status', render: r => `<span class="tag ${r.last_status === 'SUCCESS' ? 'good' : 'flat'}">${U.esc(r.last_status)}</span>` },
        { label: 'Last success', render: r => r.last_success ? U.ago(r.last_success) : 'never' },
        { label: 'Stale', render: r => r.stale ? `<span class="tag bad">${U.esc(r.stale_reason)}</span>` : '<span class="tag good">fresh</span>' },
      ], d.live.sources));
    }

    if (d.settings) {
      U.html('settingsTable', d.settings.settings.map(s => `
        <div style="display:flex;gap:8px;align-items:center;margin-bottom:6px;flex-wrap:wrap">
          <label style="min-width:160px;font-size:11.5px" class="muted">${U.esc(s.key)}</label>
          <input type="text" value="${U.esc(s.value ?? '')}" data-key="${U.esc(s.key)}"
                 data-type="${U.esc(s.type)}" style="width:150px">
          <button class="btn sm" onclick="App.saveSetting(this.previousElementSibling)">Save</button>
          <span class="faint" style="font-size:11px">${U.esc(s.description || '')}</span>
        </div>`).join(''));
    }

    if (d.sched) {
      U.html('schedBlock', `<dl class="kv">
        <dt>Running</dt><dd>${d.sched.running ? '<span class="tag good">yes</span>' : '<span class="tag warn">no</span>'}</dd>
        <dt>Timezone</dt><dd>${U.esc(d.sched.timezone)}</dd>
        ${d.sched.jobs.map(j => `<dt>${U.esc(j.id)}</dt><dd>${j.next_run ? U.date(j.next_run) + ' ' + new Date(j.next_run).toLocaleTimeString('en-IN') : '—'}</dd>`).join('')}
      </dl>
      ${Object.keys(d.sched.last_runs || {}).length ? `<div class="card-head" style="margin-top:10px"><h3>Last runs</h3></div>
        <dl class="kv">${Object.entries(d.sched.last_runs).map(([k, v]) =>
          `<dt>${U.esc(k)}</dt><dd><span class="tag ${v.status === 'SUCCESS' ? 'good' : 'bad'}">${U.esc(v.status)}</span> ${U.ago(v.finished)}</dd>`).join('')}</dl>` : ''}`);
    }

    if (d.stats) {
      U.html('statsBlock', `<dl class="kv">
        <dt>Price rows</dt><dd>${U.num(d.stats.price_rows, 0)}</dd>
        <dt>Forecast rows</dt><dd>${U.num(d.stats.forecast_rows, 0)}</dd>
        <dt>Supplier quotes</dt><dd>${d.stats.quotes}</dd>
        <dt>Transformer jobs</dt><dd>${d.stats.transformers}</dd>
        <dt>Alerts</dt><dd>${d.stats.alerts}</dd>
        <dt>History from</dt><dd>${U.date(d.stats.history_from)}</dd>
        <dt>History to</dt><dd>${U.date(d.stats.history_to)}</dd>
        ${Object.entries(d.stats.rows_by_data_class).map(([k, v]) =>
          `<dt>${U.esc(k)}</dt><dd>${U.num(v, 0)} rows</dd>`).join('')}
      </dl>`);
    }
  }

  async function saveSetting(input) {
    try {
      await API.saveSetting({ key: input.dataset.key, value: input.value,
                              value_type: input.dataset.type });
      U.toast(`Saved ${input.dataset.key}`, 'ok');
    } catch (e) { U.toast('Save failed: ' + e.message, 'err'); }
  }

  /* ------------------------------------------------------- shared cards */
  function statBlock(s, fc) {
    const v = s.volatility, b = s.band, ma = s.moving_averages, t = s.trend;
    return `<dl class="kv">
      <dt>As of</dt><dd>${U.esc(s.as_of)}</dd>
      <dt>1 day</dt><dd>${U.pct(s.changes['1D'])}</dd>
      <dt>7 days</dt><dd>${U.pct(s.changes['7D'])}</dd>
      <dt>30 days</dt><dd>${U.pct(s.changes['30D'])}</dd>
      <dt>90 days</dt><dd>${U.pct(s.changes['90D'])}</dd>
      <dt>1 year</dt><dd>${U.pct(s.changes['365D'])}</dd>
      <dt>7 DMA</dt><dd>${U.rs(ma.ma7)}</dd>
      <dt>30 DMA</dt><dd>${U.rs(ma.ma30)}</dd>
      <dt>90 DMA</dt><dd>${U.rs(ma.ma90)}</dd>
      <dt>200 DMA</dt><dd>${U.rs(ma.ma200)}</dd>
      <dt>Annualised vol</dt><dd>${U.num(v.annualised, 1)}% <span class="tag ${v.band === 'HIGH' || v.band === 'EXTREME' ? 'bad' : v.band === 'MEDIUM' ? 'warn' : 'good'}">${U.esc(v.band)}</span></dd>
      <dt>Percentile</dt><dd>${U.num(b.percentile, 0)}% <span class="tag ${b.percentile > 70 ? 'bad' : b.percentile < 30 ? 'good' : 'flat'}">${U.esc(b.zone)}</span></dd>
      <dt>RSI (14)</dt><dd>${U.num(s.momentum?.rsi14, 1)}</dd>
      ${t ? `<dt>Trend</dt><dd><b>${U.esc(t.trend)}</b> (${U.num(t.score, 0)})</dd>` : ''}
    </dl>`;
  }

  function recoCard(r) {
    return `<div style="display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin-bottom:10px">
        <span class="signal ${U.signalClass(r.signal)}">${U.esc(r.signal)}</span>
        <span class="tag ${r.confidence === 'HIGH' ? 'good' : r.confidence === 'LOW' ? 'warn' : 'info'}">${U.esc(r.confidence)} confidence</span>
        <span class="faint mono">score ${U.num(r.score, 1)}</span>
      </div>
      <ul class="reason-list">${r.reasons.map(x => `<li>${U.esc(x)}</li>`).join('')}</ul>
      <div class="card-note"><b>Suggested cover ${U.num(r.suggested_cover_pct, 0)}%</b>
        (${U.num(r.suggested_lot_mt, 2)} MT of the uncovered requirement).
        ${U.esc(r.disclaimer)}</div>`;
  }

  /* ------------------------------------------------------------ actions */
  async function refreshData(full) {
    const btn = U.el('btnRefresh');
    if (btn) { btn.disabled = true; btn.innerHTML = '<span class="spinner"></span> Refreshing'; }
    setStatus('Refreshing…', '');
    try {
      const r = await API.refresh(full);
      const ok = r.prices?.sources?.filter(s => s.status === 'SUCCESS').length || 0;
      const tot = r.prices?.sources?.length || 0;
      U.toast(`Refresh complete — ${ok}/${tot} sources returned data, ` +
              `${r.alerts?.count ?? 0} new alert(s)` +
              (full ? '. Forecast retrain running in the background.' : ''),
              ok ? 'ok' : '');
      await boot(true);
    } catch (e) {
      U.toast('Refresh failed: ' + e.message, 'err');
      setStatus('Refresh failed', 'stale');
    } finally {
      if (btn) { btn.disabled = false; btn.textContent = 'Refresh data'; }
    }
  }

  async function uploadFile(input) {
    const file = input.files?.[0];
    if (!file) return;
    const fd = new FormData();
    fd.append('file', file);
    U.html('importResult', '<div class="loading"><span class="spinner"></span> Validating…</div>');
    try {
      const res = await fetch('/api/data/import?dry_run=' +
        (U.el('dryRun')?.checked ? 'true' : 'false'), { method: 'POST', body: fd });
      const j = await res.json();
      if (!res.ok) throw new Error(j.detail || 'import failed');
      U.html('importResult', `
        <dl class="kv">
          <dt>File</dt><dd>${U.esc(j.filename)}</dd>
          <dt>Mode</dt><dd>${j.dry_run ? 'validation only' : 'imported'}</dd>
          <dt>Rows read</dt><dd>${j.rows_read}</dd>
          <dt>Rows valid</dt><dd>${j.rows_valid}</dd>
          <dt>Rows inserted</dt><dd><b>${j.rows_inserted}</b></dd>
          <dt>Duplicates in file</dt><dd>${j.duplicates_in_file}</dd>
          <dt>Already stored</dt><dd>${j.duplicates_already_stored}</dd>
          <dt>Rejected</dt><dd><b class="${j.rows_rejected ? '' : ''}">${j.rows_rejected}</b></dd>
        </dl>
        ${j.rejected?.length ? `<div class="card-head" style="margin-top:10px"><h3>Rejected rows</h3></div>
          ${U.table([{ label: 'Row', key: 'row', num: true },
                     { label: 'Reason', render: r => U.esc(r.reason) }], j.rejected)}` : ''}
        ${j.issues?.length ? `<div class="card-head" style="margin-top:10px"><h3>Quality issues</h3></div>
          ${U.table([{ label: 'Type', key: 'type' }, { label: 'Severity', key: 'severity' },
                     { label: 'Detail', render: r => U.esc(r.detail) }], j.issues.slice(0, 30))}` : ''}`);
      if (!j.dry_run && j.rows_inserted) U.toast(`Imported ${j.rows_inserted} rows`, 'ok');
    } catch (e) {
      U.html('importResult', `<div class="banner err">Import failed: ${U.esc(e.message)}</div>`);
    }
    input.value = '';
  }

  async function runWhatIf(ev) {
    ev.preventDefault();
    const f = Object.fromEntries(new FormData(ev.target).entries());
    const body = { commodity: f.commodity, scenario_price: parseFloat(f.scenario_price) };
    if (f.current_price) body.current_price = parseFloat(f.current_price);
    if (f.consumption_mt) body.consumption_mt = parseFloat(f.consumption_mt);
    if (f.quantity) body.quantity = parseInt(f.quantity, 10);
    try {
      const r = await API.whatIf(body);
      U.html('whatIfResult', `<dl class="kv">
        <dt>Current price</dt><dd>${U.rs(r.current_price)} /MT</dd>
        <dt>Scenario price</dt><dd>${U.rs(r.scenario_price)} /MT</dd>
        <dt>Price change</dt><dd><span class="chg ${U.dirClass(r.price_change)}">${U.rs(r.price_change)} (${U.pct(r.price_change_pct)})</span></dd>
        <dt>BOM consumption</dt><dd>${U.num(r.consumption_mt, 4)} MT / transformer</dd>
        <dt>Transformer quantity</dt><dd>${r.quantity}</dd>
        <dt><b>Impact / transformer</b></dt><dd><b>${U.inr(r.impact_per_transformer)}</b></dd>
        <dt><b>Total project impact</b></dt><dd><b>${U.inr(r.total_project_impact)}</b></dd>
        <dt>Reference transformer cost</dt><dd>${U.inr(r.reference_transformer_cost)}</dd>
        <dt>Transformer cost increase</dt><dd>${U.pct(r.transformer_cost_increase_pct)}</dd>
        <dt>Project cost increase</dt><dd>${U.pct(r.project_cost_increase_pct)}</dd>
      </dl><div class="card-note">${U.esc(r.formula)}</div>`);
    } catch (e) { U.toast('What-if failed: ' + e.message, 'err'); }
  }

  async function runLock(ev) {
    ev.preventDefault();
    const f = Object.fromEntries(new FormData(ev.target).entries());
    const body = { commodity: f.commodity, lock_period_days: parseInt(f.lock_period_days, 10),
                   supplier_premium: parseFloat(f.supplier_premium || 0) };
    if (f.quantity_mt) body.quantity_mt = parseFloat(f.quantity_mt);
    try {
      const r = await API.priceLock(body);
      U.html('lockResult', `<dl class="kv">
          <dt>Quantity</dt><dd>${U.num(r.quantity_mt, 3)} MT</dd>
          <dt>Current price</dt><dd>${U.rs(r.current_price)}</dd>
          <dt>Supplier premium</dt><dd>${U.rs(r.supplier_premium)}</dd>
          <dt>Lock price</dt><dd><b>${U.rs(r.lock_price)}</b></dd>
          <dt>Lock now cost</dt><dd>${U.inr(r.lock_now_cost)}</dd>
          <dt>Expected price</dt><dd>${U.rs(r.expected_price)}</dd>
          <dt>Expected wait cost</dt><dd>${U.inr(r.expected_wait_cost)}</dd>
          <dt>Annualised volatility</dt><dd>${U.num(r.annualised_volatility, 1)}%</dd>
          <dt>Horizon sigma</dt><dd>${U.num(r.horizon_sigma_pct, 2)}%</dd>
        </dl>
        ${U.table([
          { label: 'Scenario', key: 'scenario' },
          { label: 'Price', num: true, render: x => U.rs(x.price) },
          { label: 'Wait cost', num: true, render: x => U.inr(x.wait_cost) },
          { label: 'vs lock', num: true, render: x =>
              `<span class="chg ${x.vs_lock >= 0 ? 'down' : 'up'}">${U.inr(x.vs_lock)}</span>` },
          { label: 'Outcome', render: x => U.esc(x.outcome) },
        ], r.scenarios)}
        <div class="card-note"><b>Recommended lock ${U.num(r.recommended_lock_pct, 0)}%
          (${U.num(r.recommended_lock_mt, 3)} MT).</b>
          Potential saving ${U.inr(r.potential_saving)} · potential exposure
          ${U.inr(r.potential_exposure)}. Best and worst cases are the 5th and 95th
          percentiles implied by realised volatility over the lock period, not assumed
          percentages. ${U.esc(r.disclaimer)}</div>`);
    } catch (e) { U.toast('Lock analysis failed: ' + e.message, 'err'); }
  }

  /* ------------------------------------------------------------- filters */
  function bindFilters() {
    const cm = U.el('fCommodity'), pv = U.el('fProvider'), pr = U.el('fProduct');
    if (!cm) return;
    const m = state.masters;
    cm.innerHTML = m.commodities.map(c =>
      `<option value="${c.code}">${U.esc(c.name)}</option>`).join('');
    cm.value = state.filters.commodity;
    function fillDependent() {
      const c = cm.value;
      const provs = m.providers.filter(p =>
        m.products.some(x => x.commodity === c) || p.code);
      pv.innerHTML = '<option value="">All providers</option>' +
        m.providers.map(p => `<option value="${p.code}">${U.esc(p.name)}</option>`).join('');
      pr.innerHTML = '<option value="">All products</option>' +
        m.products.filter(p => p.commodity === c)
          .map(p => `<option value="${p.code}">${U.esc(p.name)}${p.grade ? ' — ' + U.esc(p.grade) : ''}</option>`).join('');
      const h = m.headline[c];
      if (h) { pv.value = h.provider || ''; pr.value = h.product || ''; }
      state.filters.provider = pv.value; state.filters.product = pr.value;
    }
    fillDependent();
    cm.onchange = () => { state.filters.commodity = cm.value; fillDependent(); renderHistorical(); };
    pv.onchange = () => { state.filters.provider = pv.value; renderHistorical(); };
    pr.onchange = () => { state.filters.product = pr.value; renderHistorical(); };
    document.querySelectorAll('#periodSeg button').forEach(b => {
      b.onclick = () => {
        document.querySelectorAll('#periodSeg button').forEach(x => x.classList.remove('active'));
        b.classList.add('active');
        state.filters.period = b.dataset.period;
        renderHistorical();
      };
    });
  }

  /* ---------------------------------------------------------------- boot */
  const renderers = {
    dashboard: renderDashboard, copper: renderCopper, aluminium: renderAluminium,
    historical: renderHistorical, forecast: renderForecast, bom: renderBom,
    quotes: renderQuotes, alerts: renderAlerts, reports: renderReports,
    settings: renderSettings,
  };

  async function boot(silent) {
    if (!silent) setStatus('Loading…', '');
    try {
      const d = await API.all({ masters: API.masters(), live: API.live(), config: API.config() });
      state.masters = d.masters; state.live = d.live; state.config = d.config;
      setBanner(d.live);
      if (d.config) {
        const n = U.el('modePill');
        if (n) {
          n.className = 'pill ' + (d.config.data_mode === 'DEMO' ? 'demo' : 'live');
          n.innerHTML = `<span class="dot"></span>${d.config.data_mode}`;
        }
      }
      bindFilters();
    } catch (e) {
      setStatus('Backend unreachable', 'stale');
      U.html('bannerHost', `<div class="banner err">
        <b>Cannot reach the backend.</b>&nbsp;Start it with
        <span class="mono">python backend/main.py</span>, or open
        <a href="standalone.html">standalone.html</a> which needs no server.</div>`);
      return;
    }
    await (renderers[state.page] || renderDashboard)();
  }

  document.addEventListener('DOMContentLoaded', () => {
    document.querySelectorAll('.nav button').forEach(b =>
      b.onclick = () => go(b.dataset.page));
    const rb = U.el('btnRefresh');
    if (rb) rb.onclick = () => refreshData(false);
    const rf = U.el('btnRefreshFull');
    if (rf) rf.onclick = () => refreshData(true);
    boot();
  });

  return { go, refreshData, uploadFile, runWhatIf, runLock, submitQuote, deleteQuote,
           ackAlert, evaluateAlerts, saveSetting, state,
           setJob: (j) => { state.bomJob = j; renderBom(); },
           setSensCommodity: (c) => { state.sensCommodity = c; renderBom(); },
           setFcCommodity: (c) => { state.fcCommodity = c; renderForecast(); } };
})();
